common:
  active_model: 'ssl' # 'svm', 'cnn', 'ssl', model to train/test
  use_comet: true
  edaic_aug: false
  seed: 42
  sample_rate: 16000
  k_folds: 5

  daic_path: 'datasets/DAIC-WOZ/'
  e_daic_path: 'datasets/E-DAIC-WOZ/'
  e1_daic_path: 'datasets/E1-DAIC-WOZ/'
  model_save_dir: "saved_models/"
  result_dir: "results/"

  eval_strategy: 'majority'
  segmentation_strategy: 'transcript'
  balance_train_set: true
  
  early_stopping_patience: 5
  early_stopping_min_delta: 0.01
  early_stopping_mode: 'max'
  gradient_accumulation_steps: 1
  epochs: 20

  # Ablation options:
  pooling_type: 'gated_attention' # 'gated_attention', 'mean', 'attention'
  use_seq_model: true

cnn:
  hyperparameter_search_mode: true
  segmentation_strategy: ['transcript', 'fixed_length']
  min_utt_seconds: 0.1
  max_utt_seconds: [3.0, 5.0]
  overlap_seconds: [1.5, 2.5]
  batch_size: [32]
  dropout_rate: [0.2, 0.3]
  learning_rate: [0.0001, 0.00005]

ssl:
  hyperparameter_search_mode: false
  run_layer_sweep: false
  max_utt_seconds: 10.0
  min_utt_seconds: 0.1
  overlap_seconds: 0.0

  use_preextracted_features: true
  ssl_model_names: 
    - 'facebook/wav2vec2-base-960h'
    - 'microsoft/wavlm-base'
    - 'facebook/hubert-base-ls960'
    - 'openai/whisper-small'
  layers_to_use: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
  # This will be ignored when run_layer_sweep is true, but keep it for single runs
  layer_to_use: 8
  # This will also be ignored and replaced by the list items
  ssl_model_name: 'facebook/wav2vec2-base-960h'
  
  feature_path: "features/"
  use_all_layers: false
  chunk_segments: [15, 10, 5]
  chunk_overlap_segments: [0, 2, 4]
  seq_model_type: ['transformer']
  seq_hidden_size: [64, 128]
  learning_rate: [0.00005, 0.00001]
  dropout_rate: [0.1, 0.2]
  seq_num_layers: [1, 2]
  transformer_nhead: 4
  batch_size: [16, 32]
  
svm:
  feature_types: ['articulation', 'phonation', 'prosody', 'combined']
  strategy: 'mean'
  kernel: ['rbf', 'linear']
  class_weight: ['balanced', null]
  C: [0.001, 0.01, 0.1, 1, 10, 100, 1000]
  gamma: [0.0001, 0.001, 0.01, 0.1, 1, 'scale', 'auto']